  name: LeetCode
  uses: lowlighter/metrics@latest
    with:
      filename: metrics.plugin.leetcode.svg
      token: NOT_NEEDED
      base: ""
      plugin_leetcode: yes
      plugin_leetcode_sections: solved, skills, recent
